id = "avalonia-zed"
name = "Avalonia"
version = "0.0.1"
schema_version = 1
authors = ["Saverin"]
description = "Avalonia support for Zed"
repository = "https://github.com/euphoo-01/avalonia_zed_extension"

languages = ["avalonia"]

[grammars.avalonia]
repository = "https://github.com/euphoo-01/avalonia_zed_extension"
commit = "79ddbd98eb23868a343938cc012d05b7bcb96d30"
path="tree-sitter-avalonia"
